export { endurance } from './tool/endurance/entry';
export type { EnduranceUI, EnduranceLocaleContent } from './tool/endurance/entry';
export { nauticalConverter } from './tool/nauticalConverter/entry';
export type { NauticalConverterUI, NauticalConverterLocaleContent } from './tool/nauticalConverter/entry';
export { sailArea } from './tool/sailArea/entry';
export type { SailAreaUI, SailAreaLocaleContent } from './tool/sailArea/entry';
export { speedConverter } from './tool/speedConverter/entry';
export type { SpeedConverterUI, SpeedConverterLocaleContent } from './tool/speedConverter/entry';
export { tideCalculator } from './tool/tideCalculator/entry';
export type { TideCalculatorUI, TideCalculatorLocaleContent } from './tool/tideCalculator/entry';
export { underKeel } from './tool/underKeel/entry';
export type { UnderKeelUI, UnderKeelLocaleContent } from './tool/underKeel/entry';
export { nauticalCategory } from './category';
import { endurance } from './tool/endurance/entry';
import { nauticalConverter } from './tool/nauticalConverter/entry';
import { sailArea } from './tool/sailArea/entry';
import { speedConverter } from './tool/speedConverter/entry';
import { tideCalculator } from './tool/tideCalculator/entry';
import { underKeel } from './tool/underKeel/entry';
export const ALL_ENTRIES = [endurance, nauticalConverter, sailArea, speedConverter, tideCalculator, underKeel];
